Revert "Add a step about happy to .github/workflows/format.yml"
This reverts commit c1ab9be240f3619c801e04615c13a2e9e9c5aea3.

The action says:

>   /home/runner/work/_temp/3e0c23ad-2c06-465f-927e-7ab182700a26.sh: line 1: happy: command not found
>   Error: Process completed with exit code 127.